spring:
  application:
    name: hyundai-handsome-mall
  config:
    import:
      -  application-datasource.yml
      -  application-jwt.yml

user:
  default:
    profile:
      img: ${DEFAULT_PROFILE_IMG}


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG



application:
  domain: ${DOMAIN}

cookie:
  domain: ${DOMAIN}
  age: ${COOKIE_AGE}

server:
  max-http-header-size: 65536