spring:

  datasource:
    primary:
      jdbc-url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g301b917317dd24_maindb_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      username: ADMIN
      password: Rnwldnd7248rnwldnd7248
      driver-class-name: oracle.jdbc.OracleDriver

    history:
      jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS=(PROTOCOL=tcps)(PORT=1522)(HOST=adb.ap-chuncheon-1.oraclecloud.com))(CONNECT_DATA=(SERVICE_NAME=g301b917317dd24_historydb_medium.adb.oraclecloud.com))(SECURITY=(SSL_SERVER_DN_MATCH=yes)))
      username: ADMIN
      password: Rnwldnd7248rnwldnd7248
      driver-class-name: oracle.jdbc.OracleDriver

  logging:
    level:
      org.hibernate.eSQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

hibernate:
  history:
    ddl-auto: update
  primary:
    ddl-auto: update
