spring:
  application:
    name: hyundai-handsome-mall

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    url: ${DATABSE_URL}

encrypt:
  key:
    access: ${ACCESS_SECRET}
    life-time: ${ACCESS_LIFETIME}