spring:
  application:
    name: hyundai-handsome-mall
  config:
    import:
      -  application-datasource.yml
      -  application-jwt.yml

user:
  default:
    profile:
      img: ${DEFAULT_PROFILE_IMG}


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG


cookie:
  application:
<<<<<<< Updated upstream
    domain: localhost
=======
    domain: http://localhost:3000
>>>>>>> Stashed changes
    age: 3000000