spring:
  datasource:
    primary:
      driver-class-name: oracle.jdbc.OracleDriver
      username: ${DATABASE_USER_NAME}
      password: ${DATABASE_USER_PASSWORD}
      url: ${DATABSE_PRIMARY_URL}

    history:
      driver-class-name: oracle.jdbc.OracleDriver
      username: ${DATABASE_USER_NAME}
      password: ${DATABASE_USER_PASSWORD}
      url: ${DATABSE_SECONDARY_URL}


