spring:
  datasource:
    primary:
      jdbc-url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g301b917317dd24_historydb_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      username: ADMIN
      password: KLWR:c#4/C3LiJ8
      driver-class-name: oracle.jdbc.OracleDriver


    history:
      jdbc-url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=g301b917317dd24_historydb_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
      username: ADMIN
      password: KLWR:c#4/C3LiJ8
      driver-class-name: oracle.jdbc.OracleDriver


